#!/bin/sh
echo "pre-commit: prettify"
HERE="$(dirname "$0")"
echo $HERE
# recruit interested filenames
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
echo $FILES
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs $HERE../../node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
